version: '3.9'

services:
  # PostgreSQL
  postgres:
    image: postgres:14.2
    container_name: cloudstorage_postgres
    restart: always
    environment:
      POSTGRES_USER: "clouduser"
      POSTGRES_PASSWORD: "cloudpassword"
      POSTGRES_DB: "cloudstorage"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloud_network

  # Redis для сессий
  redis:
    image: redis:6-alpine
    container_name: cloudstorage_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cloud_network

  # MinIO для хранения файлов
  minio:
    image: minio/minio
    container_name: cloudstorage_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9100:9000"
      - "9101:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - cloud_network


networks:
  cloud_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: